### ISSUE TITLE
Error while building this project

### ISSUE THREAD

**Issue by ghost** [tsykora/infinispan-odata-server#37]
## Building Odata4jExample Maven Webapp 1.0

Downloading: http://repository.jboss.org/nexus/content/groups/public-jboss/org/odata4j/odata4j-core/0.8.0-SNAPSHOT/maven-metadata.xml

Could not transfer metadata org.odata4j:odata4j-core:0.8.0-SNAPSHOT/maven-metadata.xml from/to JBoss (http://repository.jboss.org/nexus/content/groups/public-jboss): repository.jboss.org
Downloading: http://repository.jboss.org/nexus/content/groups/public-jboss/org/odata4j/odata4j-core/0.8.0-SNAPSHOT/odata4j-core-0.8.0-SNAPSHOT.pom

Downloading: http://repository.jboss.org/nexus/content/groups/public-jboss/org/odata4j/odata4j-jersey/0.8.0-SNAPSHOT/maven-metadata.xml

Could not transfer metadata org.odata4j:odata4j-jersey:0.8.0-SNAPSHOT/maven-metadata.xml from/to JBoss (http://repository.jboss.org/nexus/content/groups/public-jboss): repository.jboss.org
Failure to transfer org.odata4j:odata4j-jersey:0.8.0-SNAPSHOT/maven-metadata.xml from http://repository.jboss.org/nexus/content/groups/public-jboss was cached in the local repository, resolution will not be reattempted until the update interval of JBoss has elapsed or updates are forced. Original error: Could not transfer metadata org.odata4j:odata4j-jersey:0.8.0-SNAPSHOT/maven-metadata.xml from/to JBoss (http://repository.jboss.org/nexus/content/groups/public-jboss): repository.jboss.org
Downloading: http://repository.jboss.org/nexus/content/groups/public-jboss/org/odata4j/odata4j-jersey/0.8.0-SNAPSHOT/odata4j-jersey-0.8.0-SNAPSHOT.pom

---
## BUILD FAILURE

Total time: 16.427s
Finished at: Sun Sep 08 21:20:58 IST 2013
## Final Memory: 6M/113M

Failed to execute goal on project Odata4jExample: Could not resolve dependencies for project Odata4jExample:Odata4jExample:jar:1.0: Failed to collect dependencies for [org.odata4j:odata4j-core:pom:0.8.0-SNAPSHOT (compile), org.odata4j:odata4j-jersey:jar:0.8.0-SNAPSHOT (compile), org.hibernate:hibernate-entitymanager:jar:4.0.1.Final (compile), junit:junit:jar:4.8.2 (compile), org.infinispan:infinispan-core:jar:6.0.0.Alpha3 (compile)]: Failed to read artifact descriptor for org.odata4j:odata4j-core:pom:0.8.0-SNAPSHOT: Could not transfer artifact org.odata4j:odata4j-core:pom:0.8.0-SNAPSHOT from/to JBoss (http://repository.jboss.org/nexus/content/groups/public-jboss): repository.jboss.org: Unknown host repository.jboss.org -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by tsykora** [comment]
Hi,
you need to install this 0.8.0 version with support for actions and functions from Samuel.

https://bitbucket.org/svetsch/odata4j-actions
- I made some little modifications to that and install this modified 0.8.0 SNAPSHOT to my local repository.
  This project is not ready yet, this is still my playground only.
